
let USER_PAGES=[], userPageEditId=null;
async function loadUserPages(){try{USER_PAGES=(await api('/api/admin/user-pages')).pages||[];renderUserPages()}catch(e){toast(e.message,true)}}
function renderUserPages(){const el=$('userPagesList');if(!el)return;const pages=[...USER_PAGES].sort((a,b)=>(a.order||0)-(b.order||0));el.innerHTML=pages.map((p,i)=>`<div class="user-page-row"><div class="user-page-number">${i+1}</div><div class="user-page-info"><b>${esc(p.name)}</b><span>/${esc(p.id)}.html · Nav: ${esc(p.navLabel||p.name)} · ${p.enabled===false?'Disabled':'Enabled'}</span></div><div class="actions"><button class="btn primary" onclick="openUserPage('${esc(p.id)}')">Open & edit visually</button><button class="btn secondary" onclick="toggleUserPage('${esc(p.id)}',${p.enabled===false})">${p.enabled===false?'Enable':'Disable'}</button><button class="btn danger" onclick="deleteUserPage('${esc(p.id)}')">Delete</button></div></div>`).join('')||'<div class="empty">No user-panel pages. Add your first page.</div>'}
async function openUserPage(id){userPageEditId=id||null;$('userPageError').textContent='';const p=USER_PAGES.find(x=>x.id===id);if(!p&&!id){$('userPageTitle').textContent='Add page';$('upName').value='New page';$('upNav').value='New page';$('upEnabled').checked=true;$('visualEmpty').textContent='Save the new page first, then open it to edit visually.';$('visualFields').classList.add('hidden');$('userPageFrame').src='about:blank';$('userPageDrawer').classList.add('open');return}if(id){try{const d=await api('/api/admin/user-pages/'+encodeURIComponent(id));$('userPageTitle').textContent='Edit '+(d.page.name||'Page');$('upName').value=d.page.name||'';$('upNav').value=d.page.navLabel||'';$('upEnabled').checked=d.page.enabled!==false;$('visualEmpty').textContent='Click a title, paragraph, button, link or image in the page preview.';$('visualFields').classList.add('hidden');const cleanHtml=String(d.html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<base\b[^>]*>/gi,'');$('userPageFrame').srcdoc=cleanHtml.replace('<head>','<head><base href="'+location.origin+'/">')}catch(e){toast(e.message,true);return}}$('userPageDrawer').classList.add('open');setTimeout(bindVisualFrame,300)}
function closeUserPage(){if($('userPageFrame'))$('userPageFrame').src='about:blank';$('userPageDrawer').classList.remove('open');userPageEditId=null;selectedVisualEl=null}
let selectedVisualEl=null;
function bindVisualFrame(){const f=$('userPageFrame');if(!f)return;f.onload=()=>{try{const doc=f.contentDocument;doc.querySelectorAll('a').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));doc.addEventListener('click',e=>{const el=e.target.closest('h1,h2,h3,h4,h5,h6,p,span,b,strong,button,a,img,li,label,section,.hero-card,.section,.feature,.campaign,.brand-story,.service-strip,.category-card,.card');if(!el||el===doc.body||el.closest('script,style'))return;e.preventDefault();e.stopPropagation();selectVisualElement(el)},true);doc.addEventListener('mouseover',e=>{const el=e.target.closest('h1,h2,h3,h4,h5,h6,p,span,b,strong,button,a,img,li,label,section,.hero-card,.section,.feature,.campaign,.brand-story,.service-strip,.category-card,.card');if(el)el.style.outline='2px dashed #b87962'},true);doc.addEventListener('mouseout',e=>{const el=e.target.closest('h1,h2,h3,h4,h5,h6,p,span,b,strong,button,a,img,li,label,section,.hero-card,.section,.feature,.campaign,.brand-story,.service-strip,.category-card,.card');if(el&&el!==selectedVisualEl)el.style.outline=''},true)}catch(e){console.warn(e)}};if(f.contentDocument&&f.contentDocument.readyState==='complete')f.onload()}
function selectVisualElement(el){if(['SECTION','DIV'].includes(el.tagName)){const child=el.querySelector('h1,h2,h3,h4,p,a,button,img');if(child)el=child;else return}selectedVisualEl=el;document.getElementById('visualEmpty').classList.add('hidden');document.getElementById('visualFields').classList.remove('hidden');$('selectedTag').textContent=el.tagName.toLowerCase();$('visualText').value=(el.tagName==='IMG'?'':el.textContent||'').trim().slice(0,500);$('editTextField').classList.toggle('hidden',el.tagName==='IMG');$('editLinkField').classList.toggle('hidden',el.tagName!=='A');$('editImageField').classList.toggle('hidden',el.tagName!=='IMG');$('editAltField').classList.toggle('hidden',el.tagName!=='IMG');if(el.tagName==='A')$('visualHref').value=el.getAttribute('href')||'';if(el.tagName==='IMG'){$('visualSrc').value=el.getAttribute('src')||'';$('visualAlt').value=el.getAttribute('alt')||''}}
function applyVisualEdit(){if(!selectedVisualEl)return;const tag=selectedVisualEl.tagName;if(tag!=='IMG')selectedVisualEl.textContent=$('visualText').value;if(tag==='A')selectedVisualEl.setAttribute('href',$('visualHref').value);if(tag==='IMG'){selectedVisualEl.setAttribute('src',$('visualSrc').value);selectedVisualEl.setAttribute('alt',$('visualAlt').value)}selectedVisualEl.style.outline='3px solid #8d5b4c';toast('Change applied — click Save all page changes')}
function hideSelectedElement(){if(!selectedVisualEl)return;selectedVisualEl.dataset.adminHidden='true';selectedVisualEl.style.display='none';toast('Element hidden — click Save all page changes')}
async function saveVisualUserPage(){try{if(!userPageEditId)throw Error('For a new page, create it first, then open it visually.');const frame=$('userPageFrame'),doc=frame.contentDocument;doc.querySelectorAll('[data-admin-editor], [data-admin-selected]').forEach(x=>{x.removeAttribute('data-admin-editor');x.removeAttribute('data-admin-selected')});doc.querySelectorAll('*').forEach(x=>{if(x.style.outline)x.style.outline=''});doc.querySelectorAll('base').forEach(x=>x.remove());const html='<!doctype html>\n'+doc.documentElement.outerHTML;const body={name:$('upName').value.trim(),navLabel:$('upNav').value.trim(),enabled:$('upEnabled').checked,html};if(!body.name)throw Error('Page name is required');await api('/api/admin/user-pages/'+encodeURIComponent(userPageEditId),{method:'PUT',body:JSON.stringify(body)});await loadUserPages();toast('Page saved successfully');closeUserPage()}catch(e){$('userPageError').textContent=e.message}}
async function toggleUserPage(id,enabled){try{await api('/api/admin/user-pages/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({enabled})});await loadUserPages();toast(enabled?'Page enabled':'Page disabled')}catch(e){toast(e.message,true)}}
async function deleteUserPage(id){if(!confirm('Delete this user-panel page? This removes it from the User Panel editor and customer route.'))return;try{await api('/api/admin/user-pages/'+encodeURIComponent(id),{method:'DELETE'});await loadUserPages();toast('Page deleted')}catch(e){toast(e.message,true)}}

let HOME_SECTIONS={handmadeHighlights:[],flashSale:[],lovedByCustomers:[],customerFavourites:[],newArrivals:[]};
const HOME_SECTION_META={handmadeHighlights:['🧶 Handmade highlights','Main homepage picks'],flashSale:['💥 Flash Sale','Products shown in the limited-time sale section'],lovedByCustomers:['🏆 Loved by customers','Best-selling / customer-loved products'],customerFavourites:['🔥 Customer favourites','Trending favourites'],newArrivals:['🆕 New arrivals','Newest products']};
async function loadHomeSections(){try{const d=await api('/api/admin/home-sections');PRODUCTS=d.products||PRODUCTS;HOME_SECTIONS={...HOME_SECTIONS,...(d.config||{})};renderHomeSections()}catch(e){toast(e.message,true)}}
function renderHomeSections(){const el=$('homeSectionsEditor');if(!el)return;el.innerHTML=Object.entries(HOME_SECTION_META).map(([key,meta])=>{const ids=HOME_SECTIONS[key]||[];return `<div class="panel home-section-admin"><div class="page-head"><div><span class="eyebrow">HOMEPAGE COLLECTION</span><h2>${meta[0]}</h2><p>${meta[1]} · ${ids.length}/8 selected</p></div></div><div class="home-product-picker">${PRODUCTS.filter(p=>p.active!==false).map(p=>{const sel=ids.includes(p.id);return `<button type="button" class="home-product-option ${sel?'selected':''}" onclick="toggleHomeProduct('${key}','${esc(p.id)}')"><img src="${esc(p.image||'https://placehold.co/80')}" alt=""><span><b>${esc(p.name)}</b><small>${esc(p.sku||'')} · ${money(p.price)}</small></span><i>${sel?'✓':''}</i></button>`}).join('')||'<div class="empty">Add products first.</div>'}</div></div>`}).join('')}
function toggleHomeProduct(key,id){const arr=HOME_SECTIONS[key]||[];if(arr.includes(id))HOME_SECTIONS[key]=arr.filter(x=>x!==id);else{if(arr.length>=8)return toast('Maximum 8 products per section',true);HOME_SECTIONS[key]=[...arr,id]}renderHomeSections()}
async function saveHomeSections(){try{const d=await api('/api/admin/home-sections',{method:'PUT',body:JSON.stringify(HOME_SECTIONS)});HOME_SECTIONS={...HOME_SECTIONS,...d.config};renderHomeSections();toast('Homepage sections saved')}catch(e){toast(e.message,true)}}

let PRODUCTS=[],ORDERS=[],SLIDER_IDS=[],BUDGETS=[],CATEGORIES=[],INVENTORY=[],editId=null,budgetEditId=null,currentCollection="",collectionEditId=null,collectionItems=[];
const $=id=>document.getElementById(id),money=n=>"₹"+Number(n||0).toLocaleString("en-IN"),esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function api(url,opt={}){const r=await fetch(url,{credentials:"same-origin",...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
function toast(msg,error=false){const n=document.createElement("div");n.className="toast"+(error?" error":"");n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),2600)}
async function login(){try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:$('password').value})});$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadAll()}catch(e){$('loginError').textContent=e.message}}
async function boot(){try{await api('/api/admin/me');$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadAll()}catch{}}
async function logout(){await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.reload()}
async function loadAll(){await Promise.allSettled([loadDashboard(),loadOrders(),loadProducts(),loadCategories(),loadSlider(),loadHomeSections(),loadBudgets(),loadShipping(),loadInventory(),loadAnalytics(),loadSettings()]);await checkHealth()}
async function checkHealth(){try{const d=await fetch('/api/health').then(r=>r.json());$('health').textContent=d.firebase?'● Firebase connected':'● Local persistent storage';$('health').className='health '+(d.firebase?'ok':'local')}catch{$('health').textContent='● Offline';$('health').className='health bad'}}
async function loadDashboard(){try{const d=await api('/api/admin/orders'),os=d.orders||[],ps=(await api('/api/products')).products||[];ORDERS=os;PRODUCTS=ps;const rev=os.reduce((s,o)=>s+Number(o.total??o.amount??0),0);$('sOrders').textContent=os.length;$('sRevenue').textContent=money(rev);$('sPending').textContent=os.filter(o=>!['delivered','cancelled'].includes(o.status)).length;$('sProducts').textContent=ps.length;$('dash').innerHTML=os.slice(0,6).map(o=>`<div class="mini-row"><div>📦 <b>${esc(o.id)}</b><br><span>${esc(o.customer?.name||'')} · ${money(o.total??o.amount)}</span></div><span class="pill">${esc(o.status||'new')}</span></div>`).join('')||'<div class="empty">No orders yet.</div>';const map={};os.forEach(o=>(o.items||[]).forEach(i=>{map[i.id]=map[i.id]||{name:i.name,units:0};map[i.id].units+=Number(i.qty||0)}));$('dashTop').innerHTML=Object.values(map).sort((a,b)=>b.units-a.units).slice(0,6).map((x,i)=>`<div class="mini-row"><span>#${i+1} ${esc(x.name)}</span><b>${x.units} sold</b></div>`).join('')||'<div class="empty">No sales yet.</div>'}catch(e){toast(e.message,true)}}
async function loadOrders(){try{ORDERS=(await api('/api/admin/orders')).orders||[];renderOrders()}catch(e){$('ordersTable').innerHTML=`<tr><td colspan="8" class="error">${esc(e.message)}</td></tr>`}}
function renderOrders(){const q=($('orderSearch')?.value||'').toLowerCase(),sf=$('orderStatusFilter')?.value||'',pf=$('orderPaymentFilter')?.value||'';const rows=ORDERS.filter(o=>{const text=JSON.stringify(o).toLowerCase();return(!q||text.includes(q))&&(!sf||o.status===sf)&&(!pf||o.paymentMethod===pf)});$('ordersTable').innerHTML=rows.length?rows.map(o=>`<tr><td><b>${esc(o.id)}</b><br><small>${new Date(o.createdAt||Date.now()).toLocaleString()}</small></td><td>${esc(o.customer?.name||'')}<br>${esc(o.customer?.phone||'')}</td><td>${(o.items||[]).map(i=>`${esc(i.name)} × ${i.qty}`).join('<br>')}</td><td><b>${money(o.total??o.amount)}</b><br><small>Ship ${money(o.shipping)}</small></td><td>${esc(o.paymentMethod||'')}<br><small>${esc(o.paymentStatus||'')}</small></td><td><select onchange="status('${esc(o.id)}',this.value)">${['confirmed','preparing','shipped','out_for_delivery','delivered','cancelled'].map(s=>`<option value="${s}" ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td><input class="tiny" value="${esc(o.awb||'')}" placeholder="AWB" onchange="setShipping('${esc(o.id)}',this.value)"><input class="tiny" value="${esc(o.courier||'')}" placeholder="Courier" onchange="setCourier('${esc(o.id)}',this.value)"><small>${esc(o.estimatedDelivery||'')}</small></td><td><button class="btn secondary" onclick="viewOrder('${esc(o.id)}')">View</button> <button class="btn secondary" onclick="openTracking('${esc(o.id)}')">Track</button></td></tr>`).join(''):'<tr><td colspan="8">No orders found.</td></tr>'}
async function status(id,s){try{await api('/api/admin/orders/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({status:s})});await loadOrders();toast('Order status updated')}catch(e){toast(e.message,true)}}
async function setShipping(id,awb){try{await api('/api/admin/orders/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({awb})});toast('AWB saved')}catch(e){toast(e.message,true)}}
async function setCourier(id,courier){try{await api('/api/admin/orders/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({courier})});toast('Courier saved')}catch(e){toast(e.message,true)}}
function openTracking(id){const o=ORDERS.find(x=>x.id===id);if(!o)return;const awb=o.awb||'';window.open('/customer/pages/track-order.html?id='+encodeURIComponent(id)+(awb?'&awb='+encodeURIComponent(awb):''),'_blank')}
function viewOrder(id){const o=ORDERS.find(x=>x.id===id);if(!o)return;const lines=(o.items||[]).map(i=>`${i.name} × ${i.qty} — ${money(i.price*i.qty)}`).join('\n');alert(`Order ${o.id}\n\nCustomer: ${o.customer?.name||''}\nPhone: ${o.customer?.phone||''}\nAddress: ${o.customer?.address||''}\n\n${lines}\n\nSubtotal: ${money(o.subtotal)}\nShipping: ${money(o.shipping)}\nTotal: ${money(o.total??o.amount)}\nPayment: ${o.paymentMethod||''} / ${o.paymentStatus||''}\nStatus: ${o.status||''}\nAWB: ${o.awb||'Not added'}`)}
function exportOrders(){const rows=[['Order ID','Date','Customer','Phone','Amount','Payment','Payment Status','Status','AWB']];ORDERS.forEach(o=>rows.push([o.id,new Date(o.createdAt||Date.now()).toISOString(),o.customer?.name||'',o.customer?.phone||'',(o.total ?? o.amount ?? 0),o.paymentMethod||'',o.paymentStatus||'',o.status||'',o.awb||'']));const csv=rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='woollycraft-orders.csv';a.click()}
async function loadProducts(){try{PRODUCTS=(await api('/api/products')).products||[];renderProducts();fillCategorySelect();renderSlider()}catch(e){toast(e.message,true)}}
function renderProducts(){const q=($('productSearch')?.value||'').toLowerCase(),c=$('productCategoryFilter')?.value||'';const ps=PRODUCTS.filter(p=>(!q||`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(q))&&(!c||p.category===c));$('products').innerHTML=ps.map(p=>`<div class="product"><img src="${esc((p.images&&p.images[0])||p.image||'https://placehold.co/200')}"><div><b>${esc(p.name)}</b><br><strong>${esc(p.sku||'NO SKU')}</strong><br>${esc(p.category)} · ${money(p.price)} · Stock ${p.stock??0}<p>${(p.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join(' ')}</p></div><div class="actions"><button class="btn secondary" onclick="openProduct('${esc(p.id)}')">Edit</button><button class="btn danger" onclick="delProduct('${esc(p.id)}')">Delete</button></div></div>`).join('')||'<div class="empty">No products found.</div>'}
function fillCategorySelect(){const s=$('pCategory');if(!s)return;const old=s.value;s.innerHTML=CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('')+`<option>Other</option>`;if(old)s.value=old;const f=$('productCategoryFilter');if(f){const fv=f.value;f.innerHTML='<option value="">All categories</option>'+CATEGORIES.map(c=>`<option>${esc(c)}</option>`).join('');f.value=fv}}
function openProduct(id){editId=id||null;const p=PRODUCTS.find(x=>x.id===id)||{};fillCategorySelect();$('pSku').value=p.sku||'';$('pName').value=p.name||'';$('pPrice').value=p.price??'';$('pOriginal').value=p.originalPrice??'';$('pCategory').value=p.category||CATEGORIES[0]||'Other';$('pStock').value=p.stock??0;$('pBadge').value=p.badge||'HANDMADE';$('pActive').checked=p.active!==false;[...$('pTags').options].forEach(o=>o.selected=(p.tags||[]).includes(o.value));$('pDesc').value=p.description||'';$('pFile').value='';renderImagePreview(p.images?.length?p.images:(p.image?[p.image]:[]));$('productError').textContent='';$('drawer').classList.add('open')}
function renderImagePreview(images){$('imagePreview').innerHTML=(images||[]).map((u,i)=>`<div class="preview-item"><img src="${esc(u)}"><span>${i+1}</span></div>`).join('')||'<span class="muted">No images selected yet.</span>'}
$('pFile')?.addEventListener('change',()=>{const files=[...$('pFile').files].slice(0,5);Promise.all(files.map(f=>new Promise(ok=>{const r=new FileReader();r.onload=()=>ok(r.result);r.readAsDataURL(f)}))).then(renderImagePreview)})
function closeProduct(){$('drawer').classList.remove('open');editId=null}
async function saveProduct(){try{const old=PRODUCTS.find(x=>x.id===editId),files=[...$('pFile').files].slice(0,5);let images=old?.images?.length?old.images:(old?.image?[old.image]:[]);if(files.length){const fd=new FormData();files.forEach(f=>fd.append('images',f));const r=await fetch('/api/admin/upload-images',{method:'POST',body:fd,credentials:'same-origin'}),d=await r.json();if(!r.ok)throw Error(d.error||'Image upload failed');images=d.images.map(x=>x.url)}const p={sku:$('pSku').value.trim().toUpperCase(),name:$('pName').value.trim(),price:Number($('pPrice').value),originalPrice:$('pOriginal').value===''?null:Number($('pOriginal').value),category:$('pCategory').value,stock:Number($('pStock').value||0),description:$('pDesc').value.trim(),image:images[0]||'',images,active:$('pActive').checked,badge:$('pBadge').value.trim()||'HANDMADE',tags:[...$('pTags').selectedOptions].map(o=>o.value),featured:old?.featured||false,trending:old?.trending||false};await api(editId?'/api/admin/products/'+encodeURIComponent(editId):'/api/admin/products',{method:editId?'PUT':'POST',body:JSON.stringify(p)});closeProduct();await loadAll();toast('Product saved')}catch(e){$('productError').textContent=e.message}}
async function delProduct(id){if(!confirm('Delete this product?'))return;try{await api('/api/admin/products/'+encodeURIComponent(id),{method:'DELETE'});await loadAll();toast('Product deleted')}catch(e){toast(e.message,true)}}
async function loadInventory(){try{INVENTORY=(await api('/api/admin/inventory')).items||[];$('inventoryTable').innerHTML=INVENTORY.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.sku)}</td><td>${esc(p.category)}</td><td><input class="tiny" id="stock-${esc(p.id)}" value="${p.stock}"></td><td>${money(p.price)}</td><td><span class="pill ${p.stock<5?'warn':''}">${p.active?'Active':'Hidden'}</span></td><td><button class="btn secondary" onclick="saveStock('${esc(p.id)}')">Save</button></td></tr>`).join('')||'<tr><td colspan="7">No products.</td></tr>'}catch(e){toast(e.message,true)}}
async function saveStock(id){try{await api('/api/admin/inventory/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({stock:Number($('stock-'+id).value)})});await loadInventory();await loadProducts();toast('Stock updated')}catch(e){toast(e.message,true)}}
async function loadCategories(){try{CATEGORIES=(await api('/api/admin/categories')).items||[];renderCategories();fillCategorySelect()}catch(e){toast(e.message,true)}}
function renderCategories(){$('categories').innerHTML=CATEGORIES.map(c=>`<div class="budget-item"><b>${esc(c)}</b><div class="actions"><button class="btn secondary" onclick="renameCategory(${JSON.stringify(c)})">Edit</button><button class="btn danger" onclick="deleteCategory(${JSON.stringify(c)})">Delete</button></div></div>`).join('')||'<div class="empty">No categories.</div>'}
async function addCategory(){const n=prompt('Category name');if(!n)return;try{await api('/api/admin/categories',{method:'POST',body:JSON.stringify({name:n})});await loadCategories();toast('Category added')}catch(e){toast(e.message,true)}}
async function renameCategory(old){const n=prompt('New category name',old);if(!n||n===old)return;try{await api('/api/admin/categories/'+encodeURIComponent(old),{method:'PUT',body:JSON.stringify({name:n})});await loadAll();toast('Category renamed')}catch(e){toast(e.message,true)}}
async function deleteCategory(n){if(!confirm('Delete category? Products keep their current category.'))return;try{await api('/api/admin/categories/'+encodeURIComponent(n),{method:'DELETE'});await loadCategories();toast('Category deleted')}catch(e){toast(e.message,true)}}
async function loadSlider(){try{const d=await api('/api/admin/home-slider');SLIDER_IDS=d.productIds||[];renderSlider()}catch(e){toast(e.message,true)}}
function renderSlider(){if(!$('sliderProducts'))return;$('sliderCount').textContent=`${SLIDER_IDS.length} / 5 selected`;$('sliderProducts').innerHTML=PRODUCTS.map(p=>{const selected=SLIDER_IDS.includes(p.id),i=SLIDER_IDS.indexOf(p.id);return `<div class="slider-item ${selected?'selected':''}"><img src="${esc(p.image||'https://placehold.co/120')}"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.sku||'')} · ${money(p.price)} ${selected?'· Position '+(i+1):''}</div></div><div class="actions"><button class="btn ${selected?'primary':'secondary'}" onclick="toggleSlider('${esc(p.id)}')">${selected?'✓ Remove':'Add'}</button>${selected?`<button class="btn secondary" onclick="moveSlider('${esc(p.id)}',-1)" ${i===0?'disabled':''}>↑</button><button class="btn secondary" onclick="moveSlider('${esc(p.id)}',1)" ${i===SLIDER_IDS.length-1?'disabled':''}>↓</button>`:''}</div></div>`}).join('')||'<div class="empty">Add products first.</div>'}
function toggleSlider(id){if(SLIDER_IDS.includes(id))SLIDER_IDS=SLIDER_IDS.filter(x=>x!==id);else{if(SLIDER_IDS.length>=5)return toast('Maximum 5 products',true);SLIDER_IDS.push(id)}renderSlider()}
function moveSlider(id,d){const i=SLIDER_IDS.indexOf(id),j=i+d;if(i<0||j<0||j>=SLIDER_IDS.length)return;[SLIDER_IDS[i],SLIDER_IDS[j]]=[SLIDER_IDS[j],SLIDER_IDS[i]];renderSlider()}
async function saveSlider(){try{await api('/api/admin/home-slider',{method:'PUT',body:JSON.stringify({productIds:SLIDER_IDS})});await loadSlider();toast('Slider saved')}catch(e){toast(e.message,true)}}
async function loadBudgets(){try{BUDGETS=(await api('/api/admin/price-buckets')).items||[];renderBudgets()}catch(e){toast(e.message,true)}}
function renderBudgets(){$('budgets').innerHTML=BUDGETS.map(b=>`<div class="budget-item"><div><b>${esc(b.label)}</b><div class="muted">${money(b.min)} → ${b.max==null?'No maximum':money(b.max)} · ${b.active===false?'Disabled':'Enabled'}</div></div><div class="actions"><button class="btn secondary" onclick="toggleBudget('${esc(b.id)}',${b.active===false})">${b.active===false?'Enable':'Disable'}</button><button class="btn secondary" onclick="openBudget('${esc(b.id)}')">Edit</button><button class="btn danger" onclick="deleteBudget('${esc(b.id)}')">Delete</button></div></div>`).join('')||'<div class="empty">No price options.</div>'}
function openBudget(id){budgetEditId=id||null;const b=BUDGETS.find(x=>x.id===id)||{label:'',min:0,max:'',active:true};$('bLabel').value=b.label;$('bMin').value=b.min??0;$('bMax').value=b.max??'';$('bActive').checked=b.active!==false;$('budgetError').textContent='';$('budgetDrawer').classList.add('open')}
function closeBudget(){$('budgetDrawer').classList.remove('open');budgetEditId=null}
async function saveBudget(){try{const body={label:$('bLabel').value.trim(),min:Number($('bMin').value||0),max:$('bMax').value===''?null:Number($('bMax').value),active:$('bActive').checked};await api(budgetEditId?'/api/admin/price-buckets/'+encodeURIComponent(budgetEditId):'/api/admin/price-buckets',{method:budgetEditId?'PUT':'POST',body:JSON.stringify(body)});closeBudget();await loadBudgets();toast('Price option saved')}catch(e){$('budgetError').textContent=e.message}}
async function toggleBudget(id,active){try{await api('/api/admin/price-buckets/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({active})});loadBudgets()}catch(e){toast(e.message,true)}}
async function deleteBudget(id){if(!confirm('Delete this price option?'))return;try{await api('/api/admin/price-buckets/'+encodeURIComponent(id),{method:'DELETE'});loadBudgets()}catch(e){toast(e.message,true)}}
async function loadShipping(){try{const s=await api('/api/admin/shipping');$('shippingCharge').value=s.shippingCharge??49;$('freeShippingThreshold').value=s.freeShippingThreshold??'';$('estimatedDeliveryDays').value=s.estimatedDeliveryDays??5;$('freeShippingEnabled').checked=s.freeShippingEnabled!==false;updateShippingSummary()}catch(e){$('shippingError').textContent=e.message}}
function updateShippingSummary(){if(!$('shippingSummary'))return;const c=Number($('shippingCharge').value||0),f=$('freeShippingThreshold').value,d=Number($('estimatedDeliveryDays').value||0);$('shippingSummary').textContent=f!==''&&$('freeShippingEnabled').checked?`₹${c} shipping below ₹${f}; free shipping at ₹${f}+; estimated delivery ${d} days.`:`₹${c} shipping on every order; estimated delivery ${d} days.`}
async function saveShipping(){try{await api('/api/admin/shipping',{method:'PUT',body:JSON.stringify({shippingCharge:Number($('shippingCharge').value),freeShippingThreshold:$('freeShippingThreshold').value===''?null:Number($('freeShippingThreshold').value),freeShippingEnabled:$('freeShippingEnabled').checked,estimatedDeliveryDays:Number($('estimatedDeliveryDays').value)})});await loadShipping();toast('Shipping saved')}catch(e){$('shippingError').textContent=e.message}}
async function loadAnalytics(){try{const a=await api('/api/admin/analytics');$('aOrders').textContent=a.totalOrders;$('aRevenue').textContent=money(a.revenue);$('aAverage').textContent=money(a.averageOrder);$('aCustomers').textContent=a.customers;$('statusChart').innerHTML=Object.entries(a.byStatus||{}).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div><i style="width:${Math.min(100,Math.max(4,v*12))}%"></i></div><b>${v}</b></div>`).join('')||'<div class="empty">No orders.</div>';$('topProducts').innerHTML=(a.topProducts||[]).map((p,i)=>`<div class="mini-row"><span>#${i+1} ${esc(p.name)}</span><b>${p.units} units</b></div>`).join('')||'<div class="empty">No sales.</div>'}catch(e){toast(e.message,true)}}
async function loadSettings(){try{const d=await api('/api/admin/settings');$('storeName').value=d.store?.name||'WoollyCraft';$('storeEmail').value=d.store?.email||'';$('storePhone').value=d.store?.phone||'';$('storeAddress').value=d.store?.address||'';$('razorpayEnabled').checked=d.payments?.razorpayEnabled!==false;$('codEnabled').checked=d.payments?.codEnabled!==false}catch(e){toast(e.message,true)}}
async function saveSettings(){try{await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({store:{name:$('storeName').value,email:$('storeEmail').value,phone:$('storePhone').value,address:$('storeAddress').value},payments:{razorpayEnabled:$('razorpayEnabled').checked,codEnabled:$('codEnabled').checked}})});toast('Settings saved')}catch(e){$('settingsError').textContent=e.message}}
const collectionConfig={customers:['name','phone','email','city','state','pincode'],payments:['orderId','method','status','amount','transactionId'],coupons:['code','type','value','minOrder','expiry','usageLimit','active'],offers:['title','description','discount','startAt','endAt','active'],banners:['title','imageUrl','link','position','active'],reviews:['productId','customerName','rating','review','status'],invoices:['orderId','invoiceNumber','status','amount','createdAt'],adminUsers:['name','email','role','active']};
async function loadCollection(name){try{const d=await api('/api/admin/'+name);collectionItems=d.items||[];renderCollection(name)}catch(e){toast(e.message,true)}}
function renderCollection(name){const panel=document.querySelector(`[data-panel="${name}"]`);if(!panel)return;let wrap=panel.querySelector('.collection-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='collection-wrap';panel.appendChild(wrap)}const fields=collectionConfig[name]||[];wrap.innerHTML=`<div class="page-head"><div><span class="eyebrow">${name.toUpperCase()}</span><h1>${name==='adminUsers'?'Admin Users':name[0].toUpperCase()+name.slice(1)}</h1></div><div class="actions"><button class="btn secondary" onclick="loadCollection('${name}')">Refresh</button><button class="btn primary" onclick="openCollection('${name}')">+ Add</button></div></div><div class="panel table-wrap"><table class="table"><thead><tr>${fields.map(f=>`<th>${esc(f)}</th>`).join('')}<th></th></tr></thead><tbody>${collectionItems.map(it=>`<tr>${fields.map(f=>`<td>${esc(it[f]===true?'Yes':it[f]===false?'No':it[f]??'')}</td>`).join('')}<td><button class="btn secondary" onclick="openCollection('${name}','${esc(it.id)}')">Edit</button> <button class="btn danger" onclick="deleteCollection('${name}','${esc(it.id)}')">Delete</button></td></tr>`).join('')||`<tr><td colspan="${fields.length+1}">No records yet.</td></tr>`}</tbody></table></div>`}
function openCollection(name,id){currentCollection=name;collectionEditId=id||null;const item=collectionItems.find(x=>x.id===id)||{};const fields=collectionConfig[name]||[];$('collectionTitle').textContent=(id?'Edit ':'Add ')+(name==='adminUsers'?'Admin User':name.slice(0,-1).replace(/^./,x=>x.toUpperCase()));$('collectionFields').innerHTML=fields.map(f=>{const isBool=['active'].includes(f),isLong=['description','review','address'].includes(f);return `<label class="field ${isLong?'full':''}">${esc(f)}${isBool?`<input id="cf-${esc(f)}" type="checkbox" ${item[f]!==false?'checked':''}>`:isLong?`<textarea id="cf-${esc(f)}">${esc(item[f]||'')}</textarea>`:`<input id="cf-${esc(f)}" type="text" value="${esc(item[f]??'')}">`}</label>`}).join('');$('collectionError').textContent='';$('collectionDrawer').classList.add('open')}
function closeCollection(){$('collectionDrawer').classList.remove('open');currentCollection='';collectionEditId=null}
async function saveCollectionItem(){try{const name=currentCollection,item=collectionItems.find(x=>x.id===collectionEditId)||{},fields=collectionConfig[name]||[],out={...item};fields.forEach(f=>{const el=$('cf-'+f);out[f]=el?.type==='checkbox'?el.checked:el?.value||''});await api(collectionEditId?`/api/admin/${name}/${encodeURIComponent(collectionEditId)}`:`/api/admin/${name}`,{method:collectionEditId?'PUT':'POST',body:JSON.stringify(out)});closeCollection();await loadCollection(name);toast('Saved')}catch(e){$('collectionError').textContent=e.message}}
async function deleteCollection(name,id){if(!confirm('Delete this record?'))return;try{await api(`/api/admin/${name}/${encodeURIComponent(id)}`,{method:'DELETE'});loadCollection(name);toast('Deleted')}catch(e){toast(e.message,true)}}

document.querySelectorAll('.side').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.side').forEach(x=>x.classList.remove('active'));document.querySelectorAll('[data-panel]').forEach(x=>x.classList.add('hidden'));b.classList.add('active');const page=b.dataset.page;document.querySelector(`[data-panel="${page}"]`).classList.remove('hidden');if(collectionConfig[page])await loadCollection(page);if(page==='inventory')await loadInventory();if(page==='analytics')await loadAnalytics();if(page==='shipping')await loadShipping();if(page==='settings')await loadSettings();if(page==='products')await loadProducts();if(page==='slider')await loadSlider();if(page==='homeSections')await loadHomeSections();if(page==='categories')await loadCategories();if(page==='budgets')await loadBudgets();if(page==='orders')await loadOrders();if(page==='dashboard')await loadDashboard();if(page==='userPanel')await loadUserPages()});
['shippingCharge','freeShippingThreshold','estimatedDeliveryDays','freeShippingEnabled'].forEach(x=>$(x)?.addEventListener('input',updateShippingSummary));
boot();
